Repository stackabletech/nifi-operator, pull requests merged in 2021-05, with the labels that each got.

#1 Apache NiFi operator initial implementation
  .github/dependabot.yml
  .github/workflows/daily_security.yml
  .github/workflows/nightly.yml
  .github/workflows/rust.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  README.adoc
  crd/Cargo.toml
  crd/src/lib.rs
  deploy/crd/server.nifi.crd.yaml
  examples/simple-nificluster.yaml
  operator/Cargo.toml
  operator/src/error.rs
  operator/src/lib.rs
  server/Cargo.toml
  server/packaging/buildrpm.sh
  server/packaging/debian/service
  server/packaging/rpm/SOURCES/stackable-nifi-operator-server-VERSION/usr/lib/systemd/system/stackable-nifi-operator-server.service
  server/packaging/rpm/SPECS/stackable-nifi-operator-server.spec
  server/src/bin/generate_crd.rs
  server/src/main.rs
Labels: type/enhancement

#10 Remove redundant release build and introduce caching
  .github/workflows/rust.yml
Labels: priority/low, size/XS, type/enhancement

#11 Added clean command to rust build.
  .github/workflows/rust.yml
Labels: type/enhancement

#4 Support nifi cluster creation
  Cargo.lock
  README.adoc
  crd/Cargo.toml
  crd/src/lib.rs
  deploy/crd/server.nifi.crd.yaml
  examples/simple-nificluster.yaml
  operator/Cargo.toml
  operator/src/config.rs
  operator/src/error.rs
  operator/src/lib.rs
  operator/src/pod_utils.rs
  server/Cargo.toml
Labels: size/M, type/enhancement

#21 Added correct OSL-3 text and corrected yaml example in readme.
  LICENSE
  README.adoc
Labels: type/documentation

#23 Updated zookeeper dependency and fixed config map create reconcile error
  Cargo.lock
  operator/src/lib.rs
Labels: dependencies, size/S, type/bug

#20 Adds Antora docs
  README.adoc
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/dependencies.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/usage.adoc
Labels: priority/low, size/M, type/documentation

#26 Fix service path for RHEL
  server/packaging/rpm/SOURCES/stackable-nifi-operator-server-VERSION/usr/lib/systemd/system/stackable-nifi-operator-server.service
Labels: priority/critical, size/XS, type/bug

#27 Fix pod names to include node names
  operator/src/lib.rs
Labels: priority/critical, size/XS, type/bug

#31 Bring project up to current Stackable best practices
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/rust.yml
  Cargo.lock
  crd/Cargo.toml
  crd/src/lib.rs
  deploy/crd/nificluster.crd.yaml
  docs/modules/ROOT/pages/building.adoc
  operator/Cargo.toml
  server/Cargo.toml
  server/packaging/rpm/SPECS/stackable-nifi-operator-server.spec
  server/src/bin/generate_nifi_crd.rs
  server/src/main.rs
Labels: priority/low, type/enhancement
