Repository stackabletech/nifi-operator, pull requests merged in 2021-09, with the labels that each got.

#70 Switched to tags.
  Cargo.lock
  crd/Cargo.toml
  operator/Cargo.toml
  server/Cargo.toml
Labels: type/dependencies

#81 Implemented versioning from operator-rs.
  CHANGELOG.md
  Cargo.lock
  deploy/crd/nificluster.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
Labels: type/enhancement, priority/high

#83 Adapted to kube-rs 0.60 and operator-rs 0.2.2
  CHANGELOG.md
  Cargo.lock
  deploy/crd/nificluster.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator-binary/src/stackable-nifi-operator.rs
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
  rust/operator/src/monitoring.rs
Labels: priority/high, type/dependencies

#87 Use sticky scheduler.
  CHANGELOG.md
  Cargo.lock
  deploy/crd/nificluster.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
Labels: type/enhancement
