Repository stackabletech/nifi-operator, pull requests merged in 2025-03, with the labels that each got.

#758 chore: Bump Rust dependencies pre-25.3.0
  CHANGELOG.md
  Cargo.lock
  Cargo.nix
  Cargo.toml
  crate-hashes.json
  rust/operator-binary/src/security/oidc.rs
  rust/operator-binary/src/security/sensitive_key.rs
Labels: release/25.3.0

#760 chore: Update ZooKeeper to 3.9.3 pre-25.3.0
  docs/modules/nifi/examples/getting_started/getting_started.sh
  docs/modules/nifi/examples/getting_started/getting_started.sh.j2
  examples/simple-nifi-cluster.yaml
  tests/test-definition.yaml
Labels: release/25.3.0

#762 docs: Revert to 1.28.1
  docs/modules/nifi/examples/getting_started/getting_started.sh
  docs/modules/nifi/examples/getting_started/getting_started.sh.j2
  docs/modules/nifi/partials/supported-versions.adoc
Labels: scheduled-for/25.3.0

#763 docs: Add troubleshooting guide on Ingress problems
  docs/modules/nifi/pages/troubleshooting/index.adoc
Labels: scheduled-for/25.3.0

#765 docs: Document how to use ListenHTTP
  docs/modules/nifi/assets/images/listen-http-1.png
  docs/modules/nifi/assets/images/listen-http-2.png
  docs/modules/nifi/assets/images/listen-http-3.png
  docs/modules/nifi/assets/images/listen-http-4.png
  docs/modules/nifi/pages/usage_guide/exposing-processors/http.adoc
  docs/modules/nifi/pages/usage_guide/exposing-processors/index.adoc
  docs/modules/nifi/pages/usage_guide/exposing-processors/tcp.adoc
  docs/modules/nifi/partials/nav.adoc
Labels: customer-request
